{% set name = "squirrel-core" %}
{% set version = "0.18.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/squirrel-core-{{ version }}.tar.gz
  sha256: 0c3e2a918974e0392b6f99370f7d4c516296f0eb0a59d1d2ace4b8fa823eab68

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - aiohttp >=3.7.4
    - fsspec >=0.8.7
    - msgpack-python
    - msgpack-numpy
    - more-itertools
    - pluggy
    - ruamel.yaml
    - tqdm
    - numba
    - pytorch
    - gcsfs >=2021.06.0

test:
  imports:
    - squirrel
    - squirrel.catalog
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/squirrel-core/
  summary: Squirrel is a Python library that enables ML teams to share, load, and transform data in a collaborative, flexible, and efficient way.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ThomasWollmann
    - winfried-ripken
    - AlirezaSohofi
    - maik-schmidt
    - hosseinkarjoo
