{% set name = "squirrel-core" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/squirrel_core-{{ version }}.tar.gz
  sha256: 9dee110d7505ee3bb7d375dfe57512bdaeb2643d95a7c04d0e1be102f2c382f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8,<4.0
    - fsspec >=2021.7.0
    - msgpack-python ^1.0.4
    - msgpack-numpy ^0.4.8
    - more-itertools ^9.0.0
    - pluggy ^1.0.0
    - random-name ^0.1.1
    - ruamel_yaml ^0.17.21
    - tqdm ^4.64.1
    - numba ^0.56.4
    - numpy ^1.23.5
    - pyjwt ^2.4.0
    - mako ^1.2.2
    - oauthlib ^3.2.1
    - aiohttp ^3.7.4
    - adlfs <2021.10
    - odfpy ^1.4.1
    - openpyxl ^3.1.1
    - pyxlsb ^1.0.10
    - xlrd ^2.0.1
    - gcsfs >=2021.7.0
    - s3fs >=2021.7.0
    - pytorch ^1.13.1
    - zarr ^2.10.3
    - pyarrow ^10.0.1

test:
  imports:
    - squirrel
    - squirrel.catalog
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://merantix-momentum.com/technology/squirrel/
  summary: Squirrel is a Python library that enables ML teams to share, load, and transform data in a collaborative, flexible and efficient way.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ThomasWollmann
    - AlirezaSohofi
    - hosseinkarjoo
