{% set name = "squirrel-core" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9dee110d7505ee3bb7d375dfe57512bdaeb2643d95a7c04d0e1be102f2c382f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - poetry
  run:
    - python >=3.8
    - aiohttp >=3.7.4
    - fsspec >=0.8.7
    - msgpack-python
    - msgpack-numpy
    - more-itertools
    - pluggy
    - ruamel.yaml
    - tqdm
    - numba
    - pytorch
    - gcsfs >=2021.06.0

test:
  imports:
    - squirrel
    - squirrel.catalog
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/squirrel-core/
  summary: Squirrel is a Python library that enables ML teams to share, load, and transform data in a collaborative, flexible, and efficient way.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ThomasWollmann
    - AlirezaSohofi
