{% set name = "squirrel-core" %}
{% set version = "0.19.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/squirrel_core-{{ version }}.tar.gz
  sha256: de2e657de0245baf12ba680bf5e6fa777c4c101614f21820b646c75d82d39723

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8,<4.0
    - fsspec >=2021.7.0
    - msgpack-python >=1.0.4,<2.0
    - msgpack-numpy >=0.4.8,<1.0
    - more-itertools >=9.0.0,<10.0
    - pluggy >=1.0.0,<2.0
    - random-name >=0.1.1,<1.0
    - ruamel.yaml >=0.17.21,<0.18.0
    - tqdm >=4.64.1,<5.0
    - numba >=0.56.4,<1.0
    - numpy >=1.23.5,<2.0
    - pyjwt >=2.4.0,<3.0
    - mako >=1.2.2,<2.0
    - oauthlib >=3.2.1,<4.0
    - aiohttp >=3.7.4,<4.0
    - adlfs <2021.10
    - dask >=2021.7.0
    - odfpy >=1.4.1,<2.0
    - openpyxl >=3.1.1,<4.0
    - pyxlsb >=1.0.10,<2.0
    - xlrd >=2.0.1,<3.0
    - gcsfs >=2021.7.0
    - s3fs >=2021.7.0
    - pytorch >=1.13.1,<2.0
    - zarr >=2.10.3,<3.0
    - pyarrow >=10.0.1,<11.0

test:
  imports:
    - squirrel
    - squirrel.catalog
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://merantix-momentum.com/technology/squirrel/
  summary: Squirrel is a Python library that enables ML teams to share, load, and transform data in a collaborative, flexible and efficient way.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ThomasWollmann
    - winfried-ripken
    - AlirezaSohofi
    - maik-schmidt
    - hosseinkarjoo
